services:
  mongo:
    image: mongo:7
    container_name: mbm-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mbm-mongo-data:/data/db

volumes:
  mbm-mongo-data:
